<?php
/**
 * @file
 * content_product_uuid.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function content_product_uuid_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Early Drupalcamp Professional Ticket P250',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'e5cd73ac-05bc-4ef2-b1b1-bf966cf03c95',
  'type' => 'product',
  'language' => 'und',
  'created' => 1414137690,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5c4e87be-f0ef-4a97-bdfa-fce3123450dc',
  'revision_uid' => 1,
  'field_product_reference' => array(
    'und' => array(
      0 => array(
        'product_id' => 3,
      ),
    ),
  ),
  'field_body' => array(),
  'field_image' => array(),
  'metatags' => array(),
  'name' => 'admincampcebu',
  'picture' => 0,
  'data' => 'a:5:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2014-10-24 08:01:30 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Early Drupalcamp Student Ticket P150',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '9b17649b-1613-4c8b-8d63-8119cea84fdc',
  'type' => 'product',
  'language' => 'und',
  'created' => 1414137618,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '8643950a-03ff-4b00-9e29-0309f1adc552',
  'revision_uid' => 1,
  'field_product_reference' => array(
    'und' => array(
      0 => array(
        'product_id' => 4,
      ),
    ),
  ),
  'field_body' => array(),
  'field_image' => array(),
  'metatags' => array(),
  'name' => 'admincampcebu',
  'picture' => 0,
  'data' => 'a:5:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2014-10-24 08:00:18 +0000',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Early Drupalcamp Cebu official tshirt P200',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '5ff736a2-91ce-482c-b430-735da2e00fd8',
  'type' => 'product',
  'language' => 'und',
  'created' => 1414136902,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f3e25625-ef0a-47d5-9e99-75b0648fef5c',
  'revision_uid' => 1,
  'field_product_reference' => array(
    'und' => array(
      0 => array(
        'product_id' => 10,
      ),
      1 => array(
        'product_id' => 11,
      ),
      2 => array(
        'product_id' => 12,
      ),
      3 => array(
        'product_id' => 13,
      ),
    ),
  ),
  'field_body' => array(),
  'field_image' => array(),
  'metatags' => array(),
  'name' => 'admincampcebu',
  'picture' => 0,
  'data' => 'a:5:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
  'date' => '2014-10-24 07:48:22 +0000',
);
  return $nodes;
}
